import ProfilePic from "../Resourceas/Images/Notification Oval.png";
import {Profile2User, Home2} from "iconsax-react";

const todayNotifications = [
  {
    id: 1,
    user: "Karenne",
    category: "Family",
    icon: <Home2 size="16" color="gray" />,
    action: "liked your photo.",
    time: "1h",
    image: ProfilePic,
  },
  {
    id: 2,
    user: "Wade Warren",
    category: "Friend",
    icon: <Profile2User size="16" color="gray" />,
    action: "liked your photo.",
    time: "1h",
    image: ProfilePic,
  },
  {
    id: 3,
    user: "Jenny Wilson",
    category: "Friend",
    icon: <Profile2User size="16" color="gray" />,
    action: "liked your photo.",
    time: "1h",
    image: ProfilePic,
  },
];

const yesterdayNotifications = [
  {
    id: 4,
    user: "Karenne",
    category: "Family",
    icon: <Home2 size="16" color="gray" />,
    action: "liked your photo.",
    time: "Yesterday",
    image: ProfilePic,
  },
  {
    id: 5,
    user: "Karenne ",
    category: "Family",
    icon: <Home2 size="16" color="gray" />,
    action: "liked your photo.",
    time: "Yesterday",
    image: ProfilePic,
  },
  {
    id: 6,
    user: "Karenne",
    category: "Family",
    icon: <Home2 size="16" color="gray" />,
    action: "liked your photo.",
    time: "Yesterday",
    image: ProfilePic,
  },
  {
    id: 7,
    user: "Karenne",
    category: "Family",
    icon: <Home2 size="16" color="gray" />,
    action: "liked your photo.",
    time: "Yesterday",
    image: ProfilePic,
  },
  {
    id: 8,
    user: "Karenne",
    category: "Family",
    icon: <Home2 size="16" color="gray" />,
    action: "liked your photo.",
    time: "Yesterday",
    image: ProfilePic,
  },
  {
    id: 9,
    user: "Karenne",
    category: "Family",
    icon: <Home2 size="16" color="gray" />,
    action: "liked your photo.",
    time: "Yesterday",
    image: ProfilePic,
  },
  {
    id: 10,
    user: "Karenne",
    category: "Family",
    icon: <Home2 size="16" color="gray" />,
    action: "liked your photo.",
    time: "Yesterday",
    image: ProfilePic,
  },
  {
    id: 11,
    user: "Karenne",
    category: "Family",
    icon: <Home2 size="16" color="gray" />,
    action: "liked your photo.",
    time: "Yesterday",
    image: ProfilePic,
  },
  {
    id: 12,
    user: "Karenne",
    category: "Family",
    icon: <Home2 size="16" color="gray" />,
    action: "liked your photo.",
    time: "Yesterday",
    image: ProfilePic,
  },
  {
    id: 13,
    user: "Karenne",
    category: "Family",
    icon: <Home2 size="16" color="gray" />,
    action: "liked your photo.",
    time: "Yesterday",
    image: ProfilePic,
  },
  {
    id: 13,
    user: "Karenne",
    category: "Family",
    icon: <Home2 size="16" color="gray" />,
    action: "liked your photo.",
    time: "Yesterday",
    image: ProfilePic,
  },
];

export { todayNotifications, yesterdayNotifications };